[package]
name = "tree-sitter-lsp-wasi-web"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = "0.23"
tree-sitter-iec61131-3-2 = { path = "../parser-iec-61131-3-2" }
# any-rope = "1.2.5"
lsp-types = "0.97.0"
lsp-textdocument = "0.4.0"
wit-bindgen-rt = { version = "0.30.0", features = ["bitflags"] }
plc_ast = { git = "https://github.com/PLC-lang/rusty.git" }

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.component]
package = "component:tree-sitter-wasi-web"

[package.metadata.component.dependencies]