export const PrimitiveTypesDefinitions: Record<string, string> =  {
    "BOOL": "```typescript\ntype boolean\n```",
    "BYTE": "```typescript\ntype BYTE = 8-bit integer [MIN: -128, MAX: +127]\n```",
    "WORD": "```typescript\ntype WORD = Unsigned 16-bit integer [MIN: 0, MAX: +65535]\n```",
    "DWORD": "```typescript\ntype DWORD = Unsigned 32-bit integer [MIN: 0, MAX: +4294967295]\n```",
    "LWORD": "```typescript\ntype LWORD = Unsigned 64-bit integer [MIN: 0, MAX: +18446744073709551615]\n```",
    "SINT": "```typescript\ntype SINT = Signed 8-bit integer [MIN: -128, MAX: +127]\n```",
    "USINT": "```typescript\ntype USINT = Unsigned 8-bit integer [MIN: 0, MAX: +255]\n```",
    "INT": "```typescript\ntype INT = Signed 16-bit integer [MIN: -32768, MAX: +32767]\n```",
    "UINT": "```typescript\ntype UINT = Unsigned 16-bit integer [MIN: 0, MAX: +65535]\n```",
    "DINT": "```typescript\ntype DINT = Signed 32-bit integer [MIN: -2147483648, MAX: +2147483647]\n```",
    "UDINT": "```typescript\ntype UDINT = Unsigned 32-bit integer [MIN: 0, MAX: +4294967295]\n```",
    "LINT": "```typescript\ntype LINT = Signed 64-bit integer [MIN: -9223372036854775808, MAX: +9223372036854775807]\n```",
    "ULINT": "```typescript\ntype ULINT = Unsigned 64-bit integer [MIN: 0, MAX: +18446744073709551615]\n```",
    "REAL": "```typescript\ntype REAL = Single precision floating point number\n```",
    "LREAL": "```typescript\ntype LREAL = Double precision floating point number\n```",
    "TIME": "```typescript\ntype TIME = Time in milliseconds\n```",
    "LTIME": "```typescript\ntype LTIME = Long Time\n```",
    "DATE": "```typescript\ntype DATE\n```",
    "TOD": "```typescript\ntype TOD\n```",
    "DT": "```typescript\ntype DT\n```",
    "DTL": "```typescript\ntype DTL\n```",
    "STRING": "```typescript\ntype STRING\n```",
    "WSTRING": "```typescript\ntype WSTRING\n```",
}